removed test reporter

diff --git a/.github/workflows/client-ci.yml b/.github/workflows/client-ci.yml
--- a/.github/workflows/client-ci.yml
+++ b/.github/workflows/client-ci.yml
@@ -48,19 +48,19 @@ jobs:
         dotnet-version: ${{ matrix.dotnet-version }}
       if: ${{ matrix.download }}
     - name: Test with dotnet
-      run: dotnet test -f ${{ matrix.framework }} -c Release --filter "Category=Common|Category=Client" --logger "trx;LogFileName=${{ matrix.dotnet-version }}.trx" --results-directory sdk-dotnet/testresults sdk-dotnet/Src/Temporal.Sdk.sln
-    - name: Test Reporter
-      uses: dorny/test-reporter@v1.5.0
-      with:
-        name: dotnet-results-${{ matrix.dotnet-version }}
-        path: '${{ matrix.dotnet-version }}.trx'
-        working-directory: sdk-dotnet/testresults
-        reporter: dotnet-trx
-      if: success() || failure()
+      run: dotnet test -f ${{ matrix.framework }} -c Release --filter "Category=Common|Category=Client" --logger "trx;LogFileName=client-${{ matrix.dotnet-version }}.trx" --results-directory sdk-dotnet/testresults sdk-dotnet/Src/Temporal.Sdk.sln
+#    - name: Test Reporter
+#      uses: dorny/test-reporter@v1.5.0
+#      with:
+#        name: dotnet-client-results-${{ matrix.dotnet-version }}
+#        path: '${{ matrix.dotnet-version }}.trx'
+#        working-directory: sdk-dotnet/testresults
+#        reporter: dotnet-trx
+#      if: success() || failure()
     - name: Upload dotnet test results
       uses: actions/upload-artifact@v3
       with:
-        name: dotnet-results-${{ matrix.dotnet-version }}
+        name: dotnet-client-results-${{ matrix.dotnet-version }}
         path: sdk-dotnet/testresults
       # Use always() to always run this step to publish test results when there are test failures
       if: ${{ always() }}
